
// Register Package auto-generated by `reggen` containing data structure

//=============================================================================
// ETHERNET FRAMING REGISTER PACKAGE (AUTO-GENERATED)
//=============================================================================
// This package defines the register map for Ethernet frame processing and
// configuration. AUTO-GENERATED by reggen tool - DO NOT EDIT MANUALLY.
//
// REGISTER MAP:
//   0x0 (CONFIG0): MAC Address Lower 32 bits
//   0x4 (CONFIG1): MAC Address Upper 16 bits + Control bits
//                  [15:0]  - Upper MAC address
//                  [16]    - Promiscuous mode enable
//                  [17]    - PHY MDIO clock
//                  [18]    - PHY MDIO output
//                  [19]    - PHY MDIO output enable
//   0x8 (CONFIG2): Status register (read-only, hardware updates)
//   0xC (CONFIG3): Status register (read-only, hardware updates)
//
// USAGE:
//   - Imported by framing_top to access register definitions
//   - Provides type-safe register access via structs
//   - reg2hw: Software writes to registers, hardware reads
//   - hw2reg: Hardware writes to registers, software reads
//
// STRUCT TYPES:
//   - eth_framing_reg2hw_t: Register → Hardware (SW configures these)
//   - eth_framing_hw2reg_t: Hardware → Register (HW reports status)
//=============================================================================

package eth_framing_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 4;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic [31:0] q;
  } eth_framing_reg2hw_config0_reg_t;

  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } upper_mac_address;
    struct packed {
      logic        q;
    } promiscuous;
    struct packed {
      logic        q;
    } phy_mdclk;
    struct packed {
      logic        q;
    } phy_mdio_o;
    struct packed {
      logic        q;
    } phy_mdio_oe;
  } eth_framing_reg2hw_config1_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } eth_framing_hw2reg_config2_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } eth_framing_hw2reg_config3_reg_t;

  // Register -> HW type
  typedef struct packed {
    eth_framing_reg2hw_config0_reg_t config0; // [51:20]
    eth_framing_reg2hw_config1_reg_t config1; // [19:0]
  } eth_framing_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    eth_framing_hw2reg_config2_reg_t config2; // [65:33]
    eth_framing_hw2reg_config3_reg_t config3; // [32:0]
  } eth_framing_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] ETH_FRAMING_CONFIG0_OFFSET = 4'h 0;
  parameter logic [BlockAw-1:0] ETH_FRAMING_CONFIG1_OFFSET = 4'h 4;
  parameter logic [BlockAw-1:0] ETH_FRAMING_CONFIG2_OFFSET = 4'h 8;
  parameter logic [BlockAw-1:0] ETH_FRAMING_CONFIG3_OFFSET = 4'h c;

  // Register index
  typedef enum int {
    ETH_FRAMING_CONFIG0,
    ETH_FRAMING_CONFIG1,
    ETH_FRAMING_CONFIG2,
    ETH_FRAMING_CONFIG3
  } eth_framing_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] ETH_FRAMING_PERMIT [4] = '{
    4'b 1111, // index[0] ETH_FRAMING_CONFIG0
    4'b 0111, // index[1] ETH_FRAMING_CONFIG1
    4'b 1111, // index[2] ETH_FRAMING_CONFIG2
    4'b 1111  // index[3] ETH_FRAMING_CONFIG3
  };

endpackage

